apiVersion: v1
data:  
  APP_PROTOCOLO: "${APP_PROTOCOLO}"
  APP_HOST: "${APP_HOST}"
  APP_ORGAO: "${APP_ORGAO}"
  APP_ORGAO_DESCRICAO: "${APP_ORGAO_DESCRICAO}"
  APP_NOMECOMPLEMENTO: "${APP_NOMECOMPLEMENTO}"
  APP_MEMCACHED_HOST: "${APP_MEMCACHED_HOST}"
  APP_DB_TIPO: "${APP_DB_TIPO}"
  APP_DB_HOST: "${APP_DB_HOST}"
  APP_DB_PORTA: "${APP_DB_PORTA}"
  APP_DB_SIP_BASE: "${APP_DB_SIP_BASE}"
  APP_DB_SIP_USERNAME: "${APP_DB_SIP_USERNAME}"
  APP_DB_SIP_PASSWORD: "${APP_DB_SIP_PASSWORD}"
  APP_DB_SEI_BASE: "${APP_DB_SEI_BASE}"
  APP_DB_SEI_USERNAME: "${APP_DB_SEI_USERNAME}"
  APP_DB_SEI_PASSWORD: "${APP_DB_SEI_PASSWORD}"
  APP_DB_ROOT_USERNAME: "${APP_DB_ROOT_USERNAME}"
  APP_DB_ROOT_PASSWORD: "${APP_DB_ROOT_PASSWORD}"
  APP_SIP_CHAVE_ACESSO: "${APP_SIP_CHAVE_ACESSO}"
  APP_SEI_CHAVE_ACESSO: "${APP_SEI_CHAVE_ACESSO}"
  APP_SOLR_URL: "${APP_SOLR_URL}"
  APP_SOLR_CORE_PROTOCOLOS: "${APP_SOLR_CORE_PROTOCOLOS}"
  APP_SOLR_TEMPO_COMMIT_PROTOCOLOS: "${APP_SOLR_TEMPO_COMMIT_PROTOCOLOS}"
  APP_SOLR_CORE_BASECONHECIMENTO: "${APP_SOLR_CORE_BASECONHECIMENTO}"
  APP_SOLR_TEMPO_COMMIT_BASECONHECIMENTO: "${APP_SOLR_TEMPO_COMMIT_BASECONHECIMENTO}"
  APP_SOLR_CORE_PUBLICACOES: "${APP_SOLR_CORE_PUBLICACOES}"
  APP_SOLR_TEMPO_COMMIT_PUBLICACOES: "${APP_SOLR_TEMPO_COMMIT_PUBLICACOES}"
  APP_MAIL_TIPO: "${APP_MAIL_TIPO}"
  APP_MAIL_SERVIDOR: "${APP_MAIL_SERVIDOR}"
  APP_MAIL_PORTA: "${APP_MAIL_PORTA}"
  APP_MAIL_CODIFICACAO: "${APP_MAIL_CODIFICACAO}"
  APP_MAIL_MAXDESTINATARIOS: "${APP_MAIL_MAXDESTINATARIOS}"
  APP_MAIL_MAXTAMANHOANEXOSMB: "${APP_MAIL_MAXTAMANHOANEXOSMB}"
  APP_MAIL_SEGURANCA: "${APP_MAIL_SEGURANCA}"
  APP_MAIL_AUTENTICAR: "${APP_MAIL_AUTENTICAR}"
  APP_MAIL_USUARIO: "${APP_MAIL_USUARIO}"
  APP_MAIL_SENHA: "${APP_MAIL_SENHA}"
  APP_MAIL_PROTEGIDO: "${APP_MAIL_PROTEGIDO}"
  APP_FONTES_GIT_PATH: "${APP_FONTES_GIT_PATH}"
  APP_FONTES_GIT_CHECKOUT: "${APP_FONTES_GIT_CHECKOUT}"
  OPENLDAP_PRESENTE: "${OPENLDAP_PRESENTE}"
  OPENLDAP_ADMIN_PASSWORD: "${OPENLDAP_ADMIN_PASSWORD}"
  OPENLDAP_DESLIGAR_NO_ORGAO_0: "${OPENLDAP_DESLIGAR_NO_ORGAO_0}"
  MODULO_ESTATISTICAS_INSTALAR: "${MODULO_ESTATISTICAS_INSTALAR}"
  MODULO_ESTATISTICAS_VERSAO: "${MODULO_ESTATISTICAS_VERSAO}"
  MODULO_ESTATISTICAS_URL: "${MODULO_ESTATISTICAS_URL}"
  MODULO_ESTATISTICAS_SIGLA: "${MODULO_ESTATISTICAS_SIGLA}"
  MODULO_ESTATISTICAS_CHAVE: "${MODULO_ESTATISTICAS_CHAVE}"
  MODULO_WSSEI_INSTALAR: "${MODULO_WSSEI_INSTALAR}"
  MODULO_WSSEI_VERSAO: "${MODULO_WSSEI_VERSAO}"
  MODULO_WSSEI_URL_NOTIFICACAO: "${MODULO_WSSEI_URL_NOTIFICACAO}"
  MODULO_WSSEI_ID_APP: "${MODULO_WSSEI_ID_APP}"
  MODULO_WSSEI_CHAVE: "${MODULO_WSSEI_CHAVE}"
  MODULO_RESPOSTA_INSTALAR: "${MODULO_RESPOSTA_INSTALAR}"
  MODULO_RESPOSTA_VERSAO: "${MODULO_RESPOSTA_VERSAO}"
  MODULO_GESTAODOCUMENTAL_INSTALAR: "${MODULO_GESTAODOCUMENTAL_INSTALAR}"
  MODULO_GESTAODOCUMENTAL_VERSAO: "${MODULO_GESTAODOCUMENTAL_VERSAO}"
  MODULO_LOGINUNICO_INSTALAR: "${MODULO_LOGINUNICO_INSTALAR}"
  MODULO_LOGINUNICO_VERSAO: "${MODULO_LOGINUNICO_VERSAO}"
  MODULO_LOGINUNICO_CLIENTID: "${MODULO_LOGINUNICO_CLIENTID}"
  MODULO_LOGINUNICO_SECRET: "${MODULO_LOGINUNICO_SECRET}"
  MODULO_LOGINUNICO_URLPROVIDER: "${MODULO_LOGINUNICO_URLPROVIDER}"
  MODULO_LOGINUNICO_REDIRECTURL: "${MODULO_LOGINUNICO_REDIRECTURL}"
  MODULO_LOGINUNICO_URLLOGOUT: "${MODULO_LOGINUNICO_URLLOGOUT}"
  MODULO_LOGINUNICO_SCOPE: "${MODULO_LOGINUNICO_SCOPE}"
  MODULO_LOGINUNICO_URLSERVICOS: "${MODULO_LOGINUNICO_URLSERVICOS}"
  MODULO_LOGINUNICO_URLREVALIDACAO: "${MODULO_LOGINUNICO_URLREVALIDACAO}"
  MODULO_LOGINUNICO_CIENTIDVALIDACAO: "${MODULO_LOGINUNICO_CIENTIDVALIDACAO}"
  MODULO_LOGINUNICO_SECRETVALIDACAO: "${MODULO_LOGINUNICO_SECRETVALIDACAO}"
  MODULO_LOGINUNICO_ORGAO: "${MODULO_LOGINUNICO_ORGAO}"
  MODULO_ASSINATURAVANCADA_INSTALAR: "${MODULO_ASSINATURAVANCADA_INSTALAR}"
  MODULO_ASSINATURAVANCADA_VERSAO: "${MODULO_ASSINATURAVANCADA_VERSAO}"
  MODULO_ASSINATURAVANCADA_CLIENTID: "${MODULO_ASSINATURAVANCADA_CLIENTID}"
  MODULO_ASSINATURAVANCADA_SECRET: "${MODULO_ASSINATURAVANCADA_SECRET}"
  MODULO_ASSINATURAVANCADA_URLPROVIDER: "${MODULO_ASSINATURAVANCADA_URLPROVIDER}"
  MODULO_ASSINATURAVANCADA_URL_SERVICOS: "${MODULO_ASSINATURAVANCADA_URL_SERVICOS}"
  MODULO_PEN_INSTALAR: "${MODULO_PEN_INSTALAR}"
  MODULO_PEN_VERSAO: "${MODULO_PEN_VERSAO}"
  MODULO_PEN_WEBSERVICE: "${MODULO_PEN_WEBSERVICE}"
  MODULO_PEN_CERTIFICADO_SENHA: "${MODULO_PEN_CERTIFICADO_SENHA}"
  MODULO_PEN_CERTIFICADO_BASE64: "${MODULO_PEN_CERTIFICADO_BASE64}"
kind: ConfigMap
metadata:
  name: sei-app
  namespace: "${KUBERNETES_NAMESPACE}"